sudo: required
services:
  - docker

before_install:
  - docker build -t arpit/docker-react -f Dockerfile.dev .

script:
  - docker run arpit/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucker_name: 'elasticbeanstalk-us-east-2-357849634621'
  bucker_path: 'docker-react'
  on:
    branch: master
